apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: telegraph
    user: admin
    password: admin
    url: http://192.168.0.200:8086
    isDefault: true
    editable: true
